package tr.com.argela.nfv.onap.service.constant;

public enum ScenarioStatus {
    INIT,
    PROFILE_PARSING,
    PROFILE_PARSED,
    VENDOR_CREATING,
    VENDOR_CREATED,
    VENDOR_FOUND,
    VENDOR_SUBMITTED,
    VSP_FOUND,
    VSP_CREATING,
    VSP_CREATED,
    VSP_ARTIFACT_UPLOADED,
    VSP_ARTIFACT_PROCESSED,
    VSP_SUBMIT,
    VSP_TO_CSAR,
    CLOUD_COMPLEX_CREATING,
    CLOUD_COMPLEX_CREATED,
    CLOUD_COMPLEX_FOUND,
    CLOUD_REGION_CREATING,
    CLOUD_REGION_CREATED,
    CLOUD_REGION_FOUND,
    
    CLOUD_TENANT_FOUND,
    CLOUD_TENANT_CREATED,

    CLOUD_AZ_FOUND,
    CLOUD_AZ_CREATED,

    
    SERVICE_VF_CREATED,
    SERVICE_VF_FOUND,
    SERVICE_VF_CHECKIN,
    SERVICE_VF_CERTIFIED,

    SERVICE_FOUND,
    SERVICE_CREATING,
    SERVICE_CREATED,
    SERVICE_VF_ADDED,
    SERVICE_CERTIFIED,
    SERVICE_DISTRIBUTE_STARTED,
    SERVICE_DISTRIBUTE_COMPLETED,

    SERVICE_SUBSCRIPTION_COMPLETED,
    CUSTOMER_CREATED,
    CUSTOMER_FOUND,

    SERVICE_SUBSCRIPTION_CUSTOMER_FOUND,
    SERVICE_SUBSCRIPTION_CUSTOMER_CREATED,

    SERVICE_SUBSCRIPTION_CUSTOMER_TENANT_FOUND,
    SERVICE_SUBSCRIPTION_CUSTOMER_TENANT_CREATED,


    SERVICE_INSTANCE_FOUND,
    SERVICE_INSTANCE_CREATE_REQUESTED,
    SERVICE_INSTANCE_CREATED,

    VNF_FOUND,
    VNF_CREATE_REQUESTED,
    VNF_CREATED,

    VF_MODULE_FOUND,
    VF_MODULE_PRELOAD,
    VF_MODULE_CREATE_REQUESTED,
    VF_MODULE_CREATED,
    ;

}
