package tr.com.argela.nfv.onap.service.constant;

public enum ScenarioStatus {
    INIT,
    PROFILE_PARSING,
    PROFILE_PARSED,
    VENDOR_CREATING,
    VENDOR_CREATED,
    VENDOR_FOUND,
    VENDOR_SUBMITTED,
    VSP_FOUND,
    VSP_CREATING,
    VSP_CREATED,
    VSP_ARTIFACT_UPLOADED,
    VSP_ARTIFACT_PROCESSED,
    VSP_SUBMIT,
    VSP_TO_CSAR,
    CLOUD_COMPLEX_CREATING,
    CLOUD_COMPLEX_CREATED,
    CLOUD_COMPLEX_FOUND,
    CLOUD_REGION_CREATING,
    CLOUD_REGION_CREATED,
    CLOUD_REGION_FOUND,
    CLOUD_TENANT_COMPLETED,
    CLOUD_AZ_COMPLETED,
    
    SERVICE_VF_CREATING,
    SERVICE_VF_CREATED,

    SERVICE_FOUND,
    SERVICE_CREATING,
    SERVICE_CREATED,
    SERVICE_VF_ADDED,
    SERVICE_CERTIFIED,
    SERVICE_DISTRUBUTE_STARTED,
    SERVICE_DISTRUBUTE_COMPLETED,
    
    SERVICE_SUBSCRIPTION_COMPLETED,
    CUSTOMER_PROCESSED;

    ;

}
